language: java
jdk:
  - oraclejdk8
  - oraclejdk9
install:
  - ./mvnw test-compile -DskipTests
script:
  - ./mvnw test jacoco:report
after_success:
  - ./mvnw coveralls:report
notifications:
  email: false
